#ifndef LINKS_HEADER
#define LINKS_HEADER

#ifndef LINKS_LAYOUT_SET
#error "LINKS_LAYOUT_SET not defined"
#endif

#include "common.comp"

layout(set = LINKS_LAYOUT_SET, binding = 0)
readonly uniform LinksParams {
    uint m;
} links_params;

layout(set = LINKS_LAYOUT_SET, binding = 1)
buffer Links {
    coherent POINT_ID data[];
} links;

#define LEVEL_M links_params.m

#ifdef LINKS_COMPACT

layout(set = LINKS_LAYOUT_SET, binding = 2)
readonly buffer LinkOffsets {
    uint data[];
} link_offsets;

#define LINKS_START(ID) \
    link_offsets.data[ID]

#define LINKS_COUNT_AT(ID, START) \
    (link_offsets.data[ID + 1] - START)

#define GET_LINK_AT(START, I) \
    links.data[START + I]

#define LINKS_COUNT(ID) \
    LINKS_COUNT_AT(ID, LINKS_START(ID))

#define GET_LINK(ID, I) \
    GET_LINK_AT(LINKS_START(ID), I)

#else

#define LINKS_CONTAINER_OFFSET(ID) \
    ID * (LINKS_CAPACITY + 1)

#define LINKS_START(ID) \
    (LINKS_CONTAINER_OFFSET(ID) + 1)

#define LINKS_COUNT_AT(ID, START) \
    links.data[START - 1]

#define GET_LINK_AT(START, I) \
    links.data[START + I]

#define LINKS_COUNT(ID) \
    LINKS_COUNT_AT(ID, LINKS_START(ID))

#define GET_LINK(ID, I) \
    GET_LINK_AT(LINKS_START(ID), I)

#define LINKS_SET_SIZE(ID, SIZE) \
    links.data[LINKS_CONTAINER_OFFSET(ID)] = SIZE

#endif

#endif
