#version 450

#include "extensions.comp"
#include "common.comp"

layout(local_size_x = SUBGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

#define VECTOR_STORAGE_LAYOUT_SET 1
#include "vector_storage.comp"

layout(set = 0, binding = 0) readonly buffer CandidateIds {
    uint data[];
} candidate_ids;

layout(set = 0, binding = 1) readonly buffer QueryVector {
    vec4 data[];
} query_vector;

layout(set = 0, binding = 2) writeonly buffer CandidateScores {
    float data[];
} candidate_scores;

void load_query_target() {
#ifdef SINGLE_SUBGROUP_PER_VECTOR
    target_cache = VECTOR_STORAGE_QUERY_ELEMENT(query_vector.data[gl_SubgroupInvocationID]);
#else
    for (uint i = 0; i < SUBGROUPS_COUNT_PER_VECTOR; i++) {
        target_cache[i] = VECTOR_STORAGE_QUERY_ELEMENT(
            query_vector.data[i * SUBGROUP_SIZE + gl_SubgroupInvocationID]
        );
    }
#endif
}

void main() {
    uint candidate_index = SUBGROUP_ID;
    load_query_target();
    float score = similarity(candidate_ids.data[candidate_index]);
    if (subgroupElect()) {
        candidate_scores.data[candidate_index] = score;
    }
}
